"""Type stubs for the Rust ``boltra._native`` extension module."""

from typing import Any

__version__: str

def is_available() -> bool: ...
def version() -> str: ...
def parse_argv(args: list[str]) -> dict[str, Any]: ...
def cli_help() -> str: ...
